services:
  plaeng-backend:
    image: plaeng-backend
    build:
      context: ./backend
    ports:
      - 8080:8080
    networks:
      - plaeng-net
    container_name: plaeng-backend
    
  plaeng-frontend:
    image: plaeng-frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    container_name: plaeng-frontend
    networks:
      - plaeng-net
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - plaeng-net
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  plaeng-net:
    driver: bridge